export const COLORS = {
    LightTheme: {
        primary: "#66BE70",
        secundary: "#8E9392",
        tertiary: "#F5f5f5",
        quaternary: "#FFFFFF",
        background: "#f5f5f5",
        background_secundary: "#FFFFFF",
        card: "#FFFFFF",
        text: "#121212",
        text_secundary: "#333333",
        text_tertiary: "#FFFFFF",
        border: "#dddddd",
        border_secundary: "#FFFFFF",
        button_primary: "#66BE70",
        icon: "#121212",
        icon_secundary: "#8E9392",
        icon_activity: "#66BE70",
        notification: "#F4C542",
        error: "#FF6347",
    },
    DarkTheme: {
        primary: "#66BE70",
        secundary: "#8E9392",
        tertiary: "#1E1E1E",
        quaternary: "#2C2C2C",
        background: "#121212",
        background_secundary: "#1E1E1E",
        card: "#1E1E1E",
        text: "#FFFFFF",
        text_secundary: "#CCCCCC",
        text_tertiary: "#8E9392",
        border: "#333333",
        border_secundary: "#1E1E1E",
        button_primary: "#66BE70",
        icon: "#FFFFFF",
        icon_secundary: "#CCCCCC",
        icon_activity: "#66BE70",
        notification: "#F4C542",
        error: "#FF6347",
    },
};
